spring:
  session:
    store-type: redis # session的存储类型
    timeout: 30s # session超时时间. 可用单位:h小时, m:分钟, s:秒
    redis:
      flush-mode: on_save # session刷新模式. on_save: 保存时刷新，即响应结束后刷新。默认是 on_save  immediate:实时刷新
      namespace: "redis-session" # 存储 Session的命名空间，默认是spring:session

component:
  session:
    cookie-name: "sid"
  cross:
    enable: true
  security:
    enable: true
    login-url: "/login"
    logout-url: "/logout"
    shiro-filter-chain:
      - path: "/user-permission"
        filters: "crossUser,crossUriUserAuthc"
      - path: "/user"
        filters: "crossUser"
      - path: "/**"
        filters: "crossAuthc,crossKickout,crossUriAuthc"
    anon-uri-pattern-coll:
      - "/login-max"
      - "/redirect-login"
      - "/check-login"
      - "/logout-remove-remember-me"
      - "/forbidden-redirect"
      - "/force-logout-redirect"
      - "/unauthorized-redirect"
      - "/write-cookie-test"
      - "/read-cookie-test"
  swagger:
    enable: true
    title: "认证/授权组件测试"
    match-packages:
      - "org.pzy.demo.security.controller"
